### ISSUE TITLE
Undeclared dependency on unzip in zip-archive-0.3.2.2

### ISSUE THREAD

**Issue by peti** [jgm/zip-archive#41]
Here we go again ...  I report this error for, I dunno, the third time, maybe? Why is that necessary? Do you even care whether this packages compiles in Nix (and other environments with proper sandboxing)?

Anyhow, for the record:

~~~
Test suite test-zip-archive: RUNNING...
Cases: 11  Tried: 4  Errors: 0  Failures: 0  adding: LICENSE (deflated 46%)
  adding: src/ (stored 0%)
  adding: LICENSE (deflated 46%)
  adding: src/ (stored 0%)
  adding: src/Codec/ (stored 0%)
  adding: src/Codec/Archive/ (stored 0%)
  adding: src/Codec/Archive/Zip.hs (deflated 74%)
  adding: test-zip-archive.1418/test_dir_with_symlinks2/ (stored 0%)
  adding: test-zip-archive.1418/test_dir_with_symlinks2/link_to_directory (deflated 13%)
  adding: test-zip-archive.1418/test_dir_with_symlinks2/link_to_directory/file.txt (stored 0%)
  adding: test-zip-archive.1418/test_dir_with_symlinks2/link_to_file (deflated 14%)
  adding: test-zip-archive.1418/test_dir_with_symlinks2/1/ (stored 0%)
  adding: test-zip-archive.1418/test_dir_with_symlinks2/1/file.txt (stored 0%)
  adding: test-zip-archive.1418/test_dir_with_symlinks2/ (stored 0%)
  adding: test-zip-archive.1418/test_dir_with_symlinks2/link_to_directory (deflated 13%)
  adding: test-zip-archive.1418/test_dir_with_symlinks2/link_to_file (deflated 14%)
  adding: test-zip-archive.1418/test_dir_with_symlinks2/1/ (stored 0%)
  adding: test-zip-archive.1418/test_dir_with_symlinks2/1/file.txt (stored 0%)
Cases: 11  Tried: 6  Errors: 0  Failures: 0  creating: test-zip-archive.1418/dir1
  creating: test-zip-archive.1418/dir1/dir2
 inflating: test-zip-archive.1418/dir1/dir2/hello
extracting: test-zip-archive.1418/dir1/hi
Cases: 11  Tried: 7  Errors: 0  Failures: 0  creating: test-zip-archive.1418/dir3
extracting: test-zip-archive.1418/dir3/hi
Cases: 11  Tried: 10  Errors: 0  Failures: 0/bin/sh: unzip: command not found
### Error in:   10                          
callCommand: unzip ./test-zip-archive.1418/testUnzip.zip (exit 127): failed
Cases: 11  Tried: 11  Errors: 1  Failures: 0
test-zip-archive.1418/test_dir_with_symlinks2/
test-zip-archive.1418/test_dir_with_symlinks2/link_to_directory
test-zip-archive.1418/test_dir_with_symlinks2/link_to_directory/file.txt
test-zip-archive.1418/test_dir_with_symlinks2/link_to_file
test-zip-archive.1418/test_dir_with_symlinks2/1/
test-zip-archive.1418/test_dir_with_symlinks2/1/file.txt
test-zip-archive.1418/test_dir_with_symlinks2/
test-zip-archive.1418/test_dir_with_symlinks2/link_to_directory
test-zip-archive.1418/test_dir_with_symlinks2/link_to_file
test-zip-archive.1418/test_dir_with_symlinks2/1/
test-zip-archive.1418/test_dir_with_symlinks2/1/file.txt
Test suite test-zip-archive: FAIL
Test suite logged to: dist/test/zip-archive-0.3.2.2-test-zip-archive.log
~~~

**Comment by blender** [comment]
Thanks for reporting the issue @peti 

I made the change to test a feature I introduced and`unzip` is required to test the feature. As there is no list of checks to perform before merging (a part from CI builds on both Linux and Windows) this went unnoticed.

I checked the issues you have previously oped but I want not able to understand what the fix is. I have no experience with Nix packages and lack some other background too probably.

If you would be so kind to propose a fix and suggest a way this can be automatically checked, I would be more than happy to make a PR to implement your suggestions.

Please find the Travis config here: https://github.com/jgm/zip-archive/blob/master/.travis.yml

**Comment by peti** [comment]
Previous discussion took place in https://github.com/jgm/zip-archive/issues/21, which lead to a fix in https://github.com/jgm/zip-archive/pull/22, which the disappeared again: https://github.com/jgm/zip-archive/issues/35. I never really understood why the build-tools declaration was dropped.

**Comment by blender** [comment]
I see, I think input by @jgm  is needed here. I'm happy to do the work to bring this back. 

How can I test if it's working? Can anything be done to catch this via CI?

**Comment by peti** [comment]
> How can I test if it's working?

Once the Cabal file declares `Build-tools: unzip` for the test suite, everything will work fine.

> Can anything be done to catch this via CI?

Not easily, no.

**Comment by blender** [comment]
Is #42  Enough?

**Comment by peti** [comment]
No. Please take a look at https://github.com/jgm/zip-archive/pull/22.

**Comment by blender** [comment]
@peti updated. However now building with stack generates a warning: 
`Warning: Package zip-archive uses a custom Cabal build, but does not use a custom-setup stanza`

**Comment by peti** [comment]
I am sorry, but all of this has been discussed before. I appreciate your
efforts and I am happy that you are taking the issue seriously. It might
be a good idea, though, to read the tickets I've referenced in my
previous message.

**Comment by blender** [comment]
I have read through your tickets and the linked ones too. Seem everything is in place to me but probably I am missing something. I would just like to avoid breaking stackage and hackage again.

**Comment by jgm** [comment]
@blender you probably need to add a custom-setup stanza to the cabal file, as discussed under #35.

But my previous solution to the problem was to remove the use of 'zip' in the test suite (instead I just packaged a pre-made zip file).  We might want to consider just doing the simplest thing here, and just removing the tests you added that require 'zip' and 'unzip'.  Yes, these are good tests, but they also make it impossible to build the library on platforms that don't have 'zip' and 'unzip' available (and what about Windows?)

**Comment by blender** [comment]
That whole part of the test just runs `ifndef _WINDOWS` so that is not a problem as shown by the CI.

Sure I can remove the test. It seems to me that they are important though as they test actual compatibility of the archives.

I will add the custom stanza and ping again to see if the problems goes away. Hopefully we won't be breaking anything else.

**Comment by jgm** [comment]
+++ Tommaso Piazza [Jan 29 18 18:07 ]:
>   That whole part of the test just runs ifndef _WINDOWS so that is not a
>   problem as shown by the CI.
>
>   Sure I can remove the test. It seems to me that they are important
>   though as they test actual compatibility of the archives.
>
>   I will add the custom stanza and ping again to see if the problems goes
>   away. Hopefully we won't be breaking anything else.

I forgot that it's disabled anyway on Windows.
Yes, before removing the test, let's try with the custom stanza.

**Comment by jgm** [comment]
What was wrong with the idea of adding the custom stanza?  That seems much cleaner than the solution proposed in #43.

**Comment by blender** [comment]
The custom stanza required cabal > 1.24

**Comment by peti** [comment]
The `custom-setup` stanza requires `cabal-version: >= 1.10`, and it's *interpreted* by version 1.24. Since the Setup.hs script required for declaring build tools does not have any dependencies other than `base` and `Cabal` itself, old version of Cabal build run the build just fine.

**Comment by blender** [comment]
great, seems problem is solved then 🎉

**Comment by jgm** [comment]
Should be fixed in release 0.3.2.3.

**Comment by peti** [comment]
Yes, the issue is fixed in the new version. We can now derive build instructions for Nix automatically: https://github.com/NixOS/cabal2nix/commit/5ec1188d6a5bd462d624238f7af71e043ebb4cc4. Thank you very much!

**Comment by borsboom** [comment]
This appears to have broken builds on Windows (#44).
